#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 3.2.0.{build}

# version suffix, if any (e.g. '-RC1', '-beta' otherwise '')
environment:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  version_suffix: ''

#---------------------------------#
#    environment configuration    #
#---------------------------------#

nuget:
  disable_publish_on_pr: true

# Build worker image (VM template)
image: Visual Studio 2022

# enable patching of Directory.Build.props
dotnet_csproj:
  patch: true
  file: '**\*.props'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}$(version_suffix)'
  package_version: '{version}$(version_suffix)'

# Install .NET 10 SDK (not pre-installed on AppVeyor VS2022 image)
install:
- ps: |
      # Install the required .NET SDK
      Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
      ./dotnet-install.ps1 -JsonFile global.json -InstallDir 'C:\Program Files\dotnet'
      # Remove the script so it doesn't "pollute" the build
      Remove-Item -Path .\dotnet-install.ps1

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build configuration
configuration: Release

build_script:
- ps: |
    dotnet restore .\GitExtensions.GerritPlugin.sln --verbosity quiet --nologo -bl:restore.binlog

- ps: |
    dotnet publish .\GitExtensions.GerritPlugin.sln --configuration Release --no-restore --verbosity quiet --nologo -bl:msbuild.binlog

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: '**\GitExtensions.GerritPlugin.*.nupkg'
  name: NuGet
- path: '*.binlog'
  name: Binlogs

deploy:
- provider: NuGet
  name: production
  artifact: /GitExtensions.GerritPlugin.*\.nupkg/
  api_key:
    secure: Cu5mvoCI+zw9j2rAhznAyc+pqunWrR9EodrrLyufOGMF10YahzhvyQWfk72an+Fm
  skip_symbols: false
  on:
    appveyor_repo_tag: true
